### ISSUE TITLE
PROYECTO FINAL

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-final-proyecto-final-equipo-buscadores-de-datos#2]
* Roldan Uriel Arcadio Avila
* Pedro García García 
* Ariadna Monserrat López Aparicio

[REPORTE DEL PROYECTO FINAL .pdf](https://github.com/user-attachments/files/15508467/REPORTE.DEL.PROYECTO.FINAL.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
